### ISSUE TITLE
cmake failure

### ISSUE THREAD

**Issue by shaoxh** [alexgkendall/caffe-posenet#41]
I have make a build file in caffe-posenet. 
Then cd build and cmake .. 
but error occurs.
Caffe has been successfully built before with no cuda and I set caffe_option in CMakeLists of caffe-posenet project "CPU_ONLY" like "caffe_option(CPU_ONLY  "Build Caffe without CUDA support" OFF) # TODO: rename to USE_CUDA".

The question is why I still get this cuda error message. Please if anyone could help.

--   Install path      :   /home/godu/Documents/caffe-posenet/build/install
-- 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "caffe" in directory /home/godu/Documents/caffe-posenet/src/caffe

-- Configuring incomplete, errors occurred!
See also "/home/godu/Documents/caffe-posenet/build/CMakeFiles/CMakeOutput.log".
See also "/home/godu/Documents/caffe-posenet/build/CMakeFiles/CMakeError.log".

**Comment by shaoxh** [comment]
It turns out my cmake version is low. I have upgrade it to 3.14 and cmake .. is ok.
However,when I did "make " command, error still occurred.

CMake Error at cuda_compile_1_generated_absval_layer.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/godu/Documents/caffe-posenet/build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_absval_layer.cu.o



src/caffe/CMakeFiles/caffe.dir/build.make:497: recipe for target 'src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o] Error 1
CMakeFiles/Makefile2:240: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shaoxh** [comment]
It turns out that caffe in this project is slightly different with the official caffe. So we need to replace some files related to cudnn in caffe-posenet project. 
Then I followed instructions of https://github.com/DRAhmadFaraz/PoseNet-Caffe.
Like 
Replace ./include/caffe/util/cudnn.hpp with the latest version of cudnn in caffe, the corresponding cudnn.hpp. All files in ./include/caffe/layers that start with cudnn, such as cudnn_conv_layer.hpp. Replaced with the corresponding file of the same name in the latest version of caffe. Replace all files starting with cudnn, such as cudnn_lrn_layer.cu, cudnn_pooling_layer.cpp, cudnn_sigmoid_layer.cu, in ./src/caffe/layer with the corresponding file of the same name in the latest version of caffe.

finally worked!

hope this could help someone else.

**Comment by shaoxh** [comment]
Oh I finally make it.
I have made some mistakes in compiling this projects. So I am going to comment here for anyone in use.

This project have a caffe itself. So the first step is to do "[cmake ..] and [make all] and [make pycaffe] on your own.
I did not realise it until read some issue. So bad, hopefully project owner could write it somewhere in Readme file.

After I finish building this caffe, ~/.bashrc should add a line in order to specify the python this project is going to use. Here is my line.
export PYTHONPATH=$PYTHONPATH:/home/godu/Documents/caffe-posenet/python:$PYTHONPATH

Then you MUST change some lines in create_posenet_lmdb_dataset.py and test_posenet.py as the author mentioned.
Some users confront errors in this step.
You should notice that in the codes of python file, caffe_root ends with a "/".

This is one of my changes in 13 line of test_posenet.py file.
# Make sure that caffe is on the python path:
caffe_root = '/home/godu/Documents/caffe-posenet/'  # Change to your directory to caffe-posenet
import sys
sys.path.insert(0, caffe_root + 'python')
